### ISSUE TITLE
RangeError: Invalid language tag: C

### ISSUE THREAD

**Issue by mpint** [duosecurity/duo_api_nodejs#3]
Hello,

I think I found a bug in the `canonParams` function in `duo_sig.js`.  It seems that `canonParams` properly processes a request object with one property, but fails on an object with more than one property.

        var ks = Object.keys(params);
        ks.sort(function(a, b) {
            return a.localeCompare(b, 'C');
        });

When a request object with multiple properties is passed into `jsonApiCall`, like so:

      duo.jsonApiCall('post', '/auth/v2/enroll', {username: user.id, valid_secs: validForSeconds}, function(res) {
    ...
        });

an error is thrown:

    node_modules/duo_api/lib/duo_sig.js:10
        return a.localeCompare(b, 'C');
                 ^
    RangeError: Invalid language tag: C
    at String.localeCompare (native)

Can you take a look at this?  Thank you.

**Comment by bspoon** [comment]
Hi, @mpint!  Sorry that it took us so long to look at this.  Hopefully #5 takes care of this.  Cheers!
