### ISSUE TITLE
v4 roadmap

### ISSUE THREAD

**Issue by sbuys** [duosecurity/duo_api_nodejs#36]
What's the plan for upgrading this library for the new Universal prompt?

**Comment by AaronAtDuo** [comment]
@sbuys Duo is working on the Universal update to the NodeJS Web SDK and we hope to have it released early next year.

**Comment by AaronAtDuo** [comment]
@sbuys The NodeJS WebSDK4 client is released.  See https://github.com/duosecurity/duo_universal_nodejs, and it's available on NPM at https://www.npmjs.com/package/@duosecurity/duo_universal.

Thanks for using Duo!
