### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by texdc** [duosecurity/duo_api_nodejs#6]
Any plans for providing support for Typescript apps?

**Comment by AaronAtDuo** [comment]
@texdc At this time, we don't have Typescript support planned.  I'll share your request with our Product team, and I encourage you to submit a feature request to support@duosecurity.com.

Thanks for your interest in Duo!

**Comment by VictorioBerra** [comment]
I second TS support!

**Comment by sgpatel5** [comment]
Typescript support is must have!!!!
